行列演算の基礎
$$
w=(X^TX)^{-1}X^Ty
$$

上記を実現するためには
 - ベクトルの定義
 - 行列の定義
 - 転置
 - 逆行列
 - 行列積

In [23]:
import numpy as np

In [27]:
#ベクトルの定義
x = np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [37]:
# 行列の定義
X = np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [39]:
# 転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [43]:
# 逆行列
# linear algebra: 線形代数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [45]:
# 行列積
XX_inv = np.dot(X,X_inv)
print(XX_inv)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


## よくある間違いについて

In [50]:
# ベクトルは[[]]２重で囲わないと転置ができなくなる
x = np.array([1,2,3])
x

array([1, 2, 3])

In [52]:
x.T #ここで失敗する

array([1, 2, 3])

In [58]:
x = np.array([[1,2,3]])
x.T

array([[1],
       [2],
       [3]])

## Numpyでよく使う処理

In [61]:
# X = np.array([[1,2],[3,4]]) の値をshapeで確認する
row,col = X.shape

In [63]:
row

2

In [65]:
col

2

In [67]:
# やや応用
X = np.array([
    [2,3,4],
    [1,2,3]
])

In [69]:
print(X)

[[2 3 4]
 [1 2 3]]


In [71]:
X.shape

(2, 3)

In [73]:
row,col = X.shape

In [75]:
row

2

In [77]:
col

3

In [79]:
# 上記のように複数の代入も可能

In [81]:
# 上記の処理を繰り返し使うためにfor文を使う
for x in X:
    print(x)
    print('--')

[2 3 4]
--
[1 2 3]
--


## 演習問題(重回帰分析)


$$
X = \begin{bmatrix}
1 & 2 & 3 \\
1 & 2 & 5 \\
1 & 3 & 4 \\
1 & 5 & 9
\end{bmatrix}
,
y = \begin{bmatrix}
1 \\
5 \\
6 \\
8 \\
\end{bmatrix}
のとき
$$
$$
w = (X^TX)^{-1}X^Ty
$$

- Step1:$X^TX$
- Step2:$(X^TX)^{-1}$
- Step3:$X^Ty$
- Step4:$w = (X^TX)^{-1}X^Ty$

In [103]:
# Xの定義
X = np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9]
])
print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [105]:
# yの定義
y = np.array([
    [1],
    [5],
    [6],
    [8]
])

print(y)

[[1]
 [5]
 [6]
 [8]]


In [109]:
# Step1:転置する
XtX = np.dot(X.T,X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [113]:
# Step2 逆行列
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [115]:
# Step3 X(転置)とyの掛け算
Xty = np.dot(X.T,y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [123]:
# Step4 Step2とStep3の掛け算
w = np.dot(XtX_inv,Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


## Scikit-learnで重回帰分析を行ってみる

In [126]:
import sklearn

In [128]:
# 上記Anacondaの場合はimport可能。万が一ない場合は
# !pip install scikit-learn

In [142]:
# 重回帰分析のみ読み込み可能
from sklearn.linear_model import LinearRegression

In [152]:
# モデルの宣言
# 今回は1を入れて調整してるため引数にfit_intercept=Falseを設定
model = LinearRegression(fit_intercept=False)

In [154]:
# モデルの学習→パラメータの調整
model.fit(X,y)

LinearRegression(fit_intercept=False)

In [156]:
# 調整後のパラメータ
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [158]:
# 切片
model.intercept_

0.0