In [1]:
import numpy as np

In [3]:
#元の配列を5行2列の形に変換
arr1 = np.arange(10).reshape(5, 2) 

In [5]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [7]:
# 配列の内容を表示
print("arr1:")
print(arr1)

# 配列の平均値を計算して表示
mean_value = arr1.mean()
print("\n配列の平均値:", mean_value)

arr1:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

配列の平均値: 4.5


In [17]:
#これで列方向に平均をとる
arr1.mean(axis=0)

array([4., 5.])

In [23]:
#これで行方向に平均とる
arr1.mean(axis=1)

array([0.5, 2.5, 4.5, 6.5, 8.5])

In [27]:
# 標準偏差
arr1.std()

2.8722813232690143

In [29]:
# 標本標準偏差
arr1.std(ddof=1)

3.0276503540974917

In [31]:
arr2 = np.random.randn(100) #平均値0標準偏差1の標準化された乱数を発生させる（１００個分）

In [33]:
arr2

array([ 0.76942245, -0.41442344,  0.4880148 , -1.10778837, -0.66211746,
       -0.22274315, -0.74573326,  0.53481503, -0.30456098,  0.41702884,
       -1.00172805, -0.00587113,  0.20813728,  0.70897074,  1.31329533,
        0.47150723, -0.10368835, -1.32489396,  0.92174529, -0.03564433,
       -0.23682105,  1.11548813, -0.76421283,  1.33424191,  0.13756171,
        0.53987407,  0.34042818,  0.39435597,  2.04636744,  0.32638817,
        0.35612474,  0.34405438, -0.56469466,  0.35260629,  0.22570551,
        1.68413193, -0.11178741,  2.22715769, -0.70957754, -0.5653829 ,
       -1.52515931,  0.95139036,  1.23651724, -1.78397229, -0.21304038,
        0.28287046,  1.33784473, -0.4863221 ,  0.29385006, -0.19230093,
        0.33254583,  0.57580182, -0.00331551,  0.11846047,  2.03518716,
       -0.31068014, -0.50398247,  0.15787308,  0.49069057, -1.12782492,
       -0.1263146 ,  1.41108971,  1.01733704,  1.45149486,  0.6374184 ,
       -0.07614729, -0.24434101, -0.52222851,  0.13814109, -1.93

In [39]:
arr2.max()

2.2271576948516967

In [41]:
arr2.min()

-2.09716888968638

In [43]:
np.sort(arr2)

array([-2.09716889, -1.93798159, -1.78397229, -1.67453638, -1.55842795,
       -1.52515931, -1.32709799, -1.32489396, -1.32235781, -1.12782492,
       -1.10778837, -1.00172805, -0.96314471, -0.89519617, -0.85620075,
       -0.76421283, -0.74573326, -0.70957754, -0.66211746, -0.65180559,
       -0.64491932, -0.5653829 , -0.56469466, -0.52222851, -0.50651841,
       -0.50398247, -0.4863221 , -0.41442344, -0.35383172, -0.31068014,
       -0.30456098, -0.24434101, -0.23682105, -0.22274315, -0.21304038,
       -0.19230093, -0.1263146 , -0.12035366, -0.11178741, -0.10368835,
       -0.07614729, -0.03564433, -0.00587113, -0.00377766, -0.00331551,
        0.00473196,  0.0215737 ,  0.11846047,  0.13756171,  0.13814109,
        0.15787308,  0.16489423,  0.20813728,  0.22570551,  0.28287046,
        0.29385006,  0.32638817,  0.33254583,  0.34042818,  0.34405438,
        0.35260629,  0.35612474,  0.39435597,  0.39543043,  0.39945488,
        0.41702884,  0.47150723,  0.4880148 ,  0.49069057,  0.51

In [49]:
#上記のうち正のものには「TRUE」そうでないものには「FALSE」を返してみる
np.where(arr2 > 0,'TRUE','FALSE')

array(['TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE',
       'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE',
       'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE',
       'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE',
       'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE',
       'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE',
       'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE',
       'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE',
       'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE',
       'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE',
       'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE',
       'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE',
       'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE'],
      dtype='<U5')

In [51]:
#上記から正の部分だけを取得してくる
arr2[np.where(arr2 > 0)]

array([0.76942245, 0.4880148 , 0.53481503, 0.41702884, 0.20813728,
       0.70897074, 1.31329533, 0.47150723, 0.92174529, 1.11548813,
       1.33424191, 0.13756171, 0.53987407, 0.34042818, 0.39435597,
       2.04636744, 0.32638817, 0.35612474, 0.34405438, 0.35260629,
       0.22570551, 1.68413193, 2.22715769, 0.95139036, 1.23651724,
       0.28287046, 1.33784473, 0.29385006, 0.33254583, 0.57580182,
       0.11846047, 2.03518716, 0.15787308, 0.49069057, 1.41108971,
       1.01733704, 1.45149486, 0.6374184 , 0.13814109, 1.0866037 ,
       1.48224395, 1.02180232, 0.16489423, 0.60432398, 0.0215737 ,
       0.51078187, 0.95953104, 0.77113658, 0.80916145, 1.73441894,
       0.39543043, 0.39945488, 1.00572974, 0.54504893, 0.00473196])

In [53]:
arr3 = np.array([1,2,3,1,1,2,3,4])
np.unique(arr3) #重複削除

array([1, 2, 3, 4])

In [35]:
#標準化の例
# 元のデータ arr1 = [1, 2, 3, 4, 5] を標準化する方法
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

# 平均
mean = arr1.mean()

# 標準偏差（ddof=0 で母集団標準偏差を計算）
std_dev = arr1.std(ddof=0)

print("平均:", mean)
print("標準偏差:", std_dev)

平均: 3.0
標準偏差: 1.4142135623730951


In [37]:
# 標準化
z_scores = (arr1 - mean) / std_dev
print("標準化されたデータ（zスコア）:", z_scores)

標準化されたデータ（zスコア）: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
# 最初のデータ点 1 は平均より低いため、負の値（-1.414）になり、元の平均から標準偏差の約1.4倍だけ低い
# 真ん中の値 3 は元のデータの平均値なので、標準化後は0
# 最後のデータ点 5 は平均より高いので、正の値（1.414）