In [1]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3])

In [5]:
arr1

array([1, 2, 3])

In [13]:
arr2 = np.array([4,5,6])

In [15]:
arr1 + arr2 #ベクトル演算により実現できる

array([5, 7, 9])

In [19]:
arr3 = np.array([[1,2],[3,4],[5,6]]) #2つずつの要素を持ったリストをねすとしていく

In [21]:
arr3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
arr3.shape #タプルで帰ってくる(3行2列という意味)

(3, 2)

In [25]:
arr3.shape[0] #1つ目要素をとる

3

In [29]:
arr4 = np.arange(10) #0から9まででarrayを作ってくれる

In [31]:
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(9).reshape(3,3) #3行3列の配列に変換しネストさせてくれる

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
arr3.reshape(-1) #で1次元配列に変換することができる

array([1, 2, 3, 4, 5, 6])

In [45]:
#numpyでよく使われる行列
np.zeros(3) #全要素が0かつ要素数が０の配列を作る

array([0., 0., 0.])

In [47]:
np.zeros([3,3]) #全要素が0かつ3行3列の行列ができる

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.ones([3,4]) #全要素が1かつ3行4列の行列ができる

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
np.empty([3,3]) #np.zeros() や np.ones() とは異なり、配列のメモリ領域だけを確保して、値は設定しない

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.eye(5) #体格行列

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
np.random.randn(3,3) #平均値が0,標準偏差が１の正規分布に従う3行3列

array([[-1.58528773,  0.94160645, -0.6580874 ],
       [-0.23762308,  2.27032735,  0.52807462],
       [ 0.01369095, -0.10592903,  0.92284698]])